### ISSUE TITLE
Frontend JavaScript is untested

### ISSUE THREAD

**Issue by rjw57** [uisautomation/sms-webapp#103]
Investigate both unit-test ([jest](http://jestjs.io/)-based) and end-to-end (selenium?) support before the frontend grows much bigger.

**Comment by msb** [comment]
From experience with IAR, IMO there's not much value in javascript unit testing. However, I think there's definite value in some kind of end-to-end, multi-browser testing

**Comment by abrahammartin** [comment]
Moved to #144
