### ISSUE TITLE
Re-use API views for UI

### ISSUE THREAD

**Issue by rjw57** [uisautomation/sms-webapp#105]
DRF supports rendering custom HTML for API endpoints using the [TemplateHTMLRenderer](http://www.django-rest-framework.org/topics/html-and-forms/#rendering-html). Our UI views essentially call the API and poke the result into a template so I see synergy.
```python
# ui/views.py

from api import views as apiviews

class MediaView(apiviews.MediaView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'frontend_index.html'
```
And then
```html
<!-- frontend_index.html -->
<script type="application/ld+json">
{{ context | json }}
</script>
```

**Comment by abrahammartin** [comment]
we have rethink this in #168
