### ISSUE TITLE
Update ui to use mediaplatform.MediaItem objects

### ISSUE THREAD

**Issue by rjw57** [uisautomation/sms-webapp#126]
From #128

The UI should stop using ``smsjwplatform.CachedResource`` objects and instead use ``mediaplatform.MediaItem`` objects. It can then use the ``jwp_video`` related object.

Remove ``smsjwplatform.CachedResource`` model and stop ``jwpfetch`` updating them.

**Comment by abrahammartin** [comment]
Moved to Sprint 52 as unfinished in 51

**Comment by rjw57** [comment]
Not only unfinished, but un-started!

**Comment by rjw57** [comment]
(And unstarted, because it wasn't on the board.)
