### ISSUE TITLE
Add API to legacysms application

### ISSUE THREAD

**Issue by rjw57** [uisautomation/sms-webapp#131]
From #128

Provide an API in the ``legacysms`` application which allows:

1. Returning the maximum value of ``legacysms.MediaItem.last_updated_at``
2. Accepting new metadata for a media item keyed by SMS media id. It will update the ``mediaplatform.MediaItem`` object and ``legacysms.MediaItem.last_updated_at`` field. The ``last_updated_at`` field value is passed in the API call and is coped from the SMS database.
3. Return a list of all media_ids.
4. Allow deleting a media item by SMS media id. This deletes the ``legacysms.MediaItem`` object and sets the ``mediaplatform.MediaItem.deleted_at`` time.
5. Allow uploading a new media item. Takes SMS media id, ``last_updated_at`` time, a download URL and metadata. Creates a new ``legacysms.MediaItem`` object, ``mediaplatform.MediaItem`` object, calls the JWPlatform video create API with the download URL and creates the ``jwplatform.Video`` object.

**Comment by abrahammartin** [comment]
Don't need that anymore
