### ISSUE TITLE
Provide RSS feed for individual media items

### ISSUE THREAD

**Issue by rjw57** [uisautomation/sms-webapp#147]
Provide a RSS feed endpoint for media items. These should be protected by the view_permission field for the MediaItem. The RSS feed should be comply with the [iTunes requirements](https://help.apple.com/itc/podcasts_connect/#/itc1723472cb).

The feed URL should be https://hostname/media/[media-item-id].rss

**Comment by abrahammartin** [comment]
duplicated from #76
