### ISSUE TITLE
Secrets in settings

### ISSUE THREAD

**Issue by abrahammartin** [uisautomation/sms-webapp#26]
https://github.com/uisautomation/sms-webapp/blob/ab84baec44c2a45327c23658ee77bd5ac257212f/smswebapp/settings/base.py#L11

Remove all secrets from settings, load the from env vars, update docker-compose to add them to dev env, and add checks.

**Comment by rjw57** [comment]
I'll prepare a branch based on #24 since that did quite the re-jig in this area.

**Comment by rjw57** [comment]
Implemented on this branch: https://github.com/rjw57/sms-webapp/tree/remove-hardcoded-secret-key. I'll hold off on opening a PR until #24 is merged so that I can re-base on any changes in #24 which arise.
