### ISSUE TITLE
Deploy to production SMS

### ISSUE THREAD

**Issue by rjw57** [uisautomation/sms-webapp#40]

**Comment by abrahammartin** [comment]
- Reconfigure apache to serve the new SMS web application in Google Cloud only for the iframe URL for the videos
- Move stats feed from test to production
- Deploy new SMS web app to Google Cloud

**Comment by abrahammartin** [comment]
Depedency from  #34 #35 #36 #42 and #43

**Comment by abrahammartin** [comment]
This is now in https://github.com/uisautomation/sms-deploy/issues/9
