### ISSUE TITLE
separate requirements

### ISSUE THREAD

**Issue by abrahammartin** [uisautomation/sms-webapp#6]
Seems useful for test/dev but we'll never use it for prod. Separate requirements and make prod as slim possible.

https://github.com/uisautomation/sms-webapp/blob/d63400151b0d22bf552d7c1e795e1acff4238d38/requirements.txt#L6

https://github.com/uisautomation/sms-webapp/blob/d63400151b0d22bf552d7c1e795e1acff4238d38/requirements.txt#L9

**Comment by rjw57** [comment]
So, I use IPython in production a lot when running ./manage.py shell. Fair point about tox.

**Comment by abrahammartin** [comment]
solution proposed on #9
