### ISSUE TITLE
Management command to store a cache in our local database of the jwplatform metadata

### ISSUE THREAD

**Issue by abrahammartin** [uisautomation/sms-webapp#67]
Schema is generated as a django Model.
Retrieves all metadata media information from JWPlayer Management API
Inserts a video in a jsonp column
Indexing the column so can be easily searchable
Replace all of then in one go using atomic transactions
Clean up the space after the transaction

**Comment by rjw57** [comment]
I've an implementation in https://github.com/rjw57/sms-webapp/tree/issue-67-sync-metadata which is ready to review but opening a PR is blocked on #63 since my implementation builds on that work. If #63 gets merged, I'll rebase the branch linked to above and open a PR.
