### ISSUE TITLE
Google Engine

### ISSUE THREAD

**Issue by abrahammartin** [uisautomation/sms-webapp#7]
https://github.com/uisautomation/sms-webapp/blob/d63400151b0d22bf552d7c1e795e1acff4238d38/Dockerfile#L21

After reading https://github.com/GoogleCloudPlatform/python-runtime and https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml I can't see any advantage of using Google's image.

Any convincing argument?

**Comment by rjw57** [comment]
Beyond it being the image their official Django example builds from, no real argument beyond the fact that the Google image has specific support for virtualenvs. If we don't want to deploy in a virtualenv within the container, then probably no advantage.

I'll prepare a PR from the base image and you can decide.
