### ISSUE TITLE
Beta Release

### ISSUE THREAD

**Issue by rjw57** [uisautomation/sms-webapp#84]
Tracking issue for features required for BETA release.

See corresponding issue uisautomation/university-media-deploy#19.

Design docs:
* https://gist.github.com/rjw57/6a72b123bdb00595690fea323f878ced

Features:

* [ ] UMP database becomes source of truth for media item metadata
* [ ] UMP application manages JWP uploads
* [ ] UMP ingests legacy SMS data
* [ ] Playlist support

**Comment by abrahammartin** [comment]
Moved to be a milestone, not an issue
