### ISSUE TITLE
Ingest SMS collections into database

### ISSUE THREAD

**Issue by rjw57** [uisautomation/sms-webapp#87]
Add support for ingesting collection data from SMS into data model. The data is ingested by way of JWP fetch which fetches all of the channels from JWP and creates matching mediaplatform.Collection objects.

A suggestion is to use the delivery API to get the *contents* of the playlist but the management API to list what collections are present.

**Comment by abrahammartin** [comment]
I think we should use the SMS as a source of truth for Collections, not JWP.

**Comment by rjw57** [comment]
OK, then this needs to wait until sms2ump is being written.

**Comment by abrahammartin** [comment]
Outdated, collections no longer exists and we are already ingesting Channels and Playlists
